### ISSUE TITLE
Can you rename max(min)?

### ISSUE THREAD

**Issue by ztxcyk** [cppfw/r4#7]
The function "friend vector(2/3/4) max/min" in vector(2/3/4).hpp will cause a compile failure. Can you rename it?

`packages\libr4.1.0.37\build\native\include\r4\vector2.hpp(218): error C2475: “r4::vector2<T>::vector2”: Redefinition: "constexpr" descriptor mismatch`

**Comment by igagis** [comment]
I have added `#undef`'s to **libr4** version **1.0.38**, please update your package and try. Let me know if it helped to solve the problem.

**Comment by ztxcyk** [comment]
Thank you for your reply.
I updated the package to 1.0.38, but I am having other problems again.
Because my project also handles min and max via macros.
I think there should be a lot of projects that have this handling as well, and there are conflicts when using libr4.
As a powerful and versatile library, I think your changing the names of min and max is a good solution. Thanks.

**Comment by igagis** [comment]
It is a bad practice to use `min` and `max` macros defined in windows header files.
Please use `std::min` and `std::max` functions instead.

**Comment by igagis** [comment]
Also, according to https://en.cppreference.com/w/cpp/language/adl it is preferred to use `using` to import the function to the scope and then just call it like this:
````
using std::min;
auto m = min(a, b);
````
This allows ADL to use `min` function from same namespace where class of `a` and `b` is defined. See **Notes** section from the link above.

**Comment by ztxcyk** [comment]
thanks.
